title: Ghostbusters
hero_image: images/ghostbusters.png
description: Make a ghost-catching game!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters
theme: cc-prototype
listed: false
ingredient: false
duration: 1
interests: ""
technology: ""
steps:
  - title: Introduction
  - title: What you'll need
  - title: Animating a ghost
  - title: Random ghosts
  - title: Catching ghosts
  - title: Adding a score
  - title: Adding a timer
  - title: "Challenge: More objects"
