title: Ghostbusters
hero_image: images/ghostbusters.png
subtitle: Who you gonna call?
description: Use scratch to make a ghost-catching game!
original_url: https://www.codeclubprojects.org/en-GB/scratch/ghostbusters?redirect=false
theme: cc-prototype
published: true

steps:
  - title: Introduction
    duration: 10
  - title: What you'll need
    duration: 10
  - title: Animating a ghost
    duration: 25
  - title: Random ghosts
    duration: 25
  - title: Catching ghosts
    duration: 10
  - title: Adding a score
    duration: 25
  - title: Adding a timer
    duration: 25
  - title: 'Challenge: More objects'
    duration: 25
